/**
 * SIGIL — DMCA Takedown Template Generator
 *
 * Supports four template variants:
 *   generic   — universal DMCA notice (all platforms)
 *   github    — GitHub DMCA with specific contact/process info
 *   cloudflare — Cloudflare abuse report for hosted infringing content
 *   hosting   — Generic web host / ISP abuse contact template
 *
 * Free plan: generic only.
 * Pro plan: all variants.
 *
 * Template only. User must review with an attorney before sending.
 */

import React, { useState, useCallback } from 'react';
import {
  View, Text, StyleSheet, TouchableOpacity, ScrollView,
  Share, Platform, Clipboard,
} from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { Colors } from '../constants/colors';

const ClipboardAPI = Clipboard as any;

export interface DMCAData {
  contentName: string;
  contentType: string;
  ownerWallet: string;
  registrationDate: string;
  txHash: string;
  ipfsCid?: string;
  contentHash: string;
  infringingUrl: string;
  infringingPlatform: string;
  detectedAt: string;
  similarity?: number;
  allowedVariants?: string[]; // from planGating.getAllowedDMCAVariants()
}

export type TemplateVariant = 'generic' | 'github' | 'cloudflare' | 'hosting';

const VARIANTS: { id: TemplateVariant; label: string; icon: string; proOnly: boolean }[] = [
  { id: 'generic',     label: 'Generic DMCA',  icon: 'document-text-outline',     proOnly: false },
  { id: 'github',      label: 'GitHub',         icon: 'logo-github',                proOnly: true  },
  { id: 'cloudflare',  label: 'Cloudflare',     icon: 'shield-outline',             proOnly: true  },
  { id: 'hosting',     label: 'Web Host',       icon: 'server-outline',             proOnly: true  },
];

// ── Template builders ─────────────────────────────────────────────────────────

function dateStr() {
  return new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' });
}

function ownershipBlock(data: DMCAData) {
  return `ORIGINAL WORK

Title: ${data.contentName}
Type: ${data.contentType}
Registration Date: ${data.registrationDate}
Blockchain Registration: Polygon Mainnet
Transaction Hash: ${data.txHash}
${data.ipfsCid ? `IPFS Metadata: https://ipfs.io/ipfs/${data.ipfsCid}` : ''}
Content Hash (SHA-256): ${data.contentHash}
Verification: https://polygonscan.com/tx/${data.txHash}`;
}

function infringingBlock(data: DMCAData) {
  return `INFRINGING MATERIAL

URL: ${data.infringingUrl}
Platform: ${data.infringingPlatform}
Date Detected: ${data.detectedAt}
${data.similarity !== undefined ? `Similarity Score: ${data.similarity}% (automated analysis)` : ''}`;
}

function legalFooter(data: DMCAData) {
  return `I have a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law.

I swear, under penalty of perjury, that the information in this notification is accurate and that I am the copyright owner or am authorized to act on behalf of the copyright owner.

Contact / Wallet Address: ${data.ownerWallet}

LEGAL DISCLAIMER: This notice is provided for informational purposes. SIGIL's blockchain registration provides a timestamped record of your claim but does not constitute legal proof of copyright ownership. Consult a qualified attorney before sending this notice.

───────────────────────────────────────────────
Generated by SIGIL — https://polygonscan.com/tx/${data.txHash}`;
}

function buildGeneric(data: DMCAData): string {
  return `DMCA TAKEDOWN NOTICE
Date: ${dateStr()}

To: DMCA Agent / Legal Team of ${data.infringingPlatform}

NOTICE OF COPYRIGHT INFRINGEMENT UNDER 17 U.S.C. § 512

I am the owner, or authorized agent of the owner, of the copyrighted work described below.

───────────────────────────────────────────────
${ownershipBlock(data)}

───────────────────────────────────────────────
${infringingBlock(data)}

───────────────────────────────────────────────
DECLARATION

I request that you immediately remove or disable access to the infringing material listed above.

${legalFooter(data)}`;
}

function buildGitHub(data: DMCAData): string {
  return `GITHUB DMCA TAKEDOWN NOTICE
Date: ${dateStr()}

To: GitHub DMCA Agent
Email: copyright@github.com
Submit via: https://support.github.com/contact/dmca_takedown

NOTICE OF COPYRIGHT INFRINGEMENT UNDER 17 U.S.C. § 512(c)

I am the copyright owner (or authorized agent) of the work described below.

───────────────────────────────────────────────
${ownershipBlock(data)}

───────────────────────────────────────────────
INFRINGING GITHUB CONTENT

Repository / File URL: ${data.infringingUrl}
Date Detected: ${data.detectedAt}
${data.similarity !== undefined ? `Similarity Score: ${data.similarity}% (automated analysis)` : ''}

Please remove or disable access to the above content.

If this content is in a fork, please also address forks containing the same material.

───────────────────────────────────────────────
COUNTER-NOTICE INFORMATION

Under 17 U.S.C. § 512(g), the alleged infringer may file a counter-notification. I understand that GitHub will restore the content unless I file a court action within 10-14 business days.

───────────────────────────────────────────────
DECLARATION

${legalFooter(data)}`;
}

function buildCloudflare(data: DMCAData): string {
  return `CLOUDFLARE ABUSE REPORT — COPYRIGHT INFRINGEMENT
Date: ${dateStr()}

Submit via: https://abuse.cloudflare.com/
Type: DMCA / Copyright Infringement

To: Cloudflare Trust & Safety

I am the copyright owner (or authorized agent) of the work described below, and I believe Cloudflare's services are being used to host or proxy infringing content.

───────────────────────────────────────────────
${ownershipBlock(data)}

───────────────────────────────────────────────
INFRINGING CONTENT (hosted/proxied by Cloudflare)

URL: ${data.infringingUrl}
Platform / Site: ${data.infringingPlatform}
Date Detected: ${data.detectedAt}
${data.similarity !== undefined ? `Similarity Score: ${data.similarity}%` : ''}

Note: I understand Cloudflare is an intermediary. I request Cloudflare disclose the hosting provider and/or take appropriate action under their ToS.

───────────────────────────────────────────────
DECLARATION

${legalFooter(data)}`;
}

function buildHosting(data: DMCAData): string {
  const host = data.infringingPlatform || 'the hosting provider';
  return `DMCA TAKEDOWN NOTICE — WEB HOSTING PROVIDER
Date: ${dateStr()}

To: Abuse Department / DMCA Agent of ${host}
(Find contact at: https://www.whois.com/whois/${data.infringingUrl.split('/')[2] ?? ''})

NOTICE OF COPYRIGHT INFRINGEMENT UNDER 17 U.S.C. § 512

I am the copyright owner (or authorized agent) of the work described below. I request the immediate removal or disabling of access to infringing content hosted on your servers.

───────────────────────────────────────────────
${ownershipBlock(data)}

───────────────────────────────────────────────
${infringingBlock(data)}

Server / Host: ${host}
IP / Domain: ${data.infringingUrl.split('/')[2] ?? 'see URL above'}

Requested Action: Immediate removal or disabling of access to the infringing content. If you are a downstream provider, please forward this notice to the content host.

───────────────────────────────────────────────
DECLARATION

${legalFooter(data)}`;
}

const BUILDERS: Record<TemplateVariant, (data: DMCAData) => string> = {
  generic:    buildGeneric,
  github:     buildGitHub,
  cloudflare: buildCloudflare,
  hosting:    buildHosting,
};

// ── Component ─────────────────────────────────────────────────────────────────

interface Props {
  data: DMCAData;
}

export default function DMCATemplate({ data }: Props) {
  const [expanded, setExpanded] = useState(false);
  const [copied, setCopied] = useState(false);
  const [activeVariant, setActiveVariant] = useState<TemplateVariant>('generic');

  const allowedVariants = data.allowedVariants ?? ['generic'];
  const text = BUILDERS[activeVariant](data);

  const handleCopy = useCallback(() => {
    try { ClipboardAPI.setString(text); }
    catch { Share.share({ message: text }).catch(() => {}); }
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }, [text]);

  const handleShare = useCallback(() => {
    Share.share({ message: text, title: `DMCA Notice — ${data.contentName}` }).catch(() => {});
  }, [text, data.contentName]);

  return (
    <View style={s.card}>
      {/* Header */}
      <TouchableOpacity style={s.header} onPress={() => setExpanded((v) => !v)} activeOpacity={0.8}>
        <View style={s.headerLeft}>
          <Ionicons name="document-text-outline" size={18} color="#F97316" />
          <Text style={s.headerTitle}>DMCA Takedown Notice</Text>
        </View>
        <Ionicons name={expanded ? 'chevron-up' : 'chevron-down'} size={16} color={Colors.textMuted} />
      </TouchableOpacity>

      {/* Disclaimer */}
      <View style={s.disclaimerRow}>
        <Ionicons name="information-circle-outline" size={13} color="#6B7280" />
        <Text style={s.disclaimerText}>
          Template only. Review with a qualified attorney before sending.
        </Text>
      </View>

      {/* Variant tabs */}
      <ScrollView
        horizontal
        showsHorizontalScrollIndicator={false}
        style={s.variantScroll}
        contentContainerStyle={s.variantRow}
      >
        {VARIANTS.map((v) => {
          const allowed = allowedVariants.includes(v.id);
          const active = activeVariant === v.id;
          return (
            <TouchableOpacity
              key={v.id}
              style={[s.variantTab, active && s.variantTabActive, !allowed && s.variantTabLocked]}
              onPress={() => {
                if (!allowed) return;
                setActiveVariant(v.id);
              }}
              activeOpacity={allowed ? 0.8 : 1}
            >
              <Ionicons
                name={allowed ? (v.icon as any) : 'lock-closed-outline'}
                size={12}
                color={active ? '#F97316' : allowed ? Colors.textMuted : '#374151'}
              />
              <Text style={[s.variantLabel, active && s.variantLabelActive, !allowed && s.variantLabelLocked]}>
                {v.label}
              </Text>
            </TouchableOpacity>
          );
        })}
      </ScrollView>

      {/* Preview */}
      {expanded && (
        <ScrollView
          style={s.previewScroll}
          nestedScrollEnabled
          showsVerticalScrollIndicator={false}
        >
          <Text style={s.previewText} selectable>{text}</Text>
        </ScrollView>
      )}

      {/* Actions */}
      <View style={s.actions}>
        <TouchableOpacity style={s.actionBtn} onPress={handleCopy} activeOpacity={0.85}>
          <Ionicons name={copied ? 'checkmark-outline' : 'copy-outline'} size={15} color={copied ? '#22C55E' : Colors.textMuted} />
          <Text style={[s.actionText, copied && { color: '#22C55E' }]}>{copied ? 'Copied!' : 'Copy'}</Text>
        </TouchableOpacity>
        <TouchableOpacity style={s.actionBtn} onPress={handleShare} activeOpacity={0.85}>
          <Ionicons name="share-outline" size={15} color={Colors.textMuted} />
          <Text style={s.actionText}>Share</Text>
        </TouchableOpacity>
        <TouchableOpacity style={s.actionBtn} onPress={() => setExpanded((v) => !v)} activeOpacity={0.85}>
          <Ionicons name="eye-outline" size={15} color={Colors.textMuted} />
          <Text style={s.actionText}>{expanded ? 'Hide' : 'Preview'}</Text>
        </TouchableOpacity>
      </View>
    </View>
  );
}

const s = StyleSheet.create({
  card: { backgroundColor: '#1E1E1E', borderRadius: 16, borderWidth: 1, borderColor: '#F9731633', overflow: 'hidden' },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', padding: 16 },
  headerLeft: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  headerTitle: { fontSize: 14, fontWeight: '700', color: '#FFFFFF' },
  disclaimerRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 6, paddingHorizontal: 16, paddingBottom: 10 },
  disclaimerText: { flex: 1, fontSize: 11, color: '#6B7280', lineHeight: 16, fontStyle: 'italic' },
  variantScroll: { borderTopWidth: 1, borderTopColor: '#2A2A2A', borderBottomWidth: 1, borderBottomColor: '#2A2A2A' },
  variantRow: { flexDirection: 'row', paddingHorizontal: 12, paddingVertical: 8, gap: 8 },
  variantTab: {
    flexDirection: 'row', alignItems: 'center', gap: 5,
    paddingHorizontal: 10, paddingVertical: 6,
    borderRadius: 8, borderWidth: 1, borderColor: '#2A2A2A',
    backgroundColor: '#161616',
  },
  variantTabActive: { borderColor: '#F97316AA', backgroundColor: '#F9731611' },
  variantTabLocked: { opacity: 0.4 },
  variantLabel: { fontSize: 11, color: Colors.textMuted, fontWeight: '600' },
  variantLabelActive: { color: '#F97316' },
  variantLabelLocked: { color: '#374151' },
  previewScroll: {
    maxHeight: 280, marginHorizontal: 16, marginTop: 12, marginBottom: 4,
    backgroundColor: '#131313', borderRadius: 10, padding: 12,
    borderWidth: 1, borderColor: '#2A2A2A',
  },
  previewText: { fontSize: 11, color: '#9CA3AF', lineHeight: 18, fontFamily: Platform.OS === 'ios' ? 'Courier New' : 'monospace' },
  actions: { flexDirection: 'row', borderTopWidth: 1, borderTopColor: '#2A2A2A' },
  actionBtn: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, paddingVertical: 12, borderRightWidth: 1, borderRightColor: '#2A2A2A' },
  actionText: { fontSize: 12, color: '#9CA3AF', fontWeight: '600' },
});
